[project]
version = "0.1.0"
name = "crawlly"
dependencies = [
    # Include the following dependencies in the final package: httpx, beautiful soup, selenium, asyncio, csv
    "httpx",
    "beautifulsoup4",
    "selenium",
    "asyncio",
    "delorean",
    "parse",
    "feedparser",
]